FROM python:3.9-slim

WORKDIR /app

# Copia o arquivo de dependências antes de copiar o código
COPY requirements.txt /app/requirements.txt

# Instala as dependências
RUN pip install -r requirements.txt

# Agora copia o código da aplicação
COPY operations/app.py /app/app.py

CMD ["python", "app.py"]
